---

openapi: 3.0.3
info:
  title: Winetime API Documentation
  version: 0.0.1
  description: |
    This project is a course project for the Programmable Web Project course. 
    
    The API stores data about wine and its attributes, such as grapes, producers and production regions.
    It's designed and implemented in the way that user can fetch any kind of data about wines etc. without
    the need to register as a user. To add more wines into database or modify the existing data, user needs to register.
    
    Current implementation doesn't limit the user based on role what they can do, that's under planning.
    Email for user isn't either compulsory since we yet don't support user communication through email.
    
    API uses Bearer token based authentication which is implemented with JWT, user needs to add the login details to header
    or it's stored to cookies.
  license:
    name: MIT
  contact:
    email: tanja.setamaa@student.oulu.fi

tags:
  - name: User
    description: Operations to create, get or delete user, login or logout. Provides the security for data modifications.
  - name: Wine
    description: Wine operations to get wine or wines, create, update or delete wine with required access token.
  - name: Wine type
    description: Wine type operations to get wine type or wine types, create, update or delete wine type with required access token.
  - name: Producer
    description: Producer operations to get producer or producers, create, update or delete producer with required access token.
  - name: Grape
    description: Grape operations to get grape or grapes, create, update or delete grape with required access token.
  - name: Region
    description: Region operations to get region or regions, create, update or delete region with required access token.
  - name: Country
    description: Country operations to get country or countries, create, update or delete country with required access token.

servers:
- url: https://wine-time-api.herokuapp.com/api

paths:
  /login:
    $ref: paths/login.yml
  /logout:
    $ref: paths/logout.yml
  /register:
    $ref: paths/register.yml
  /user/{username}:
    $ref: paths/user_{username}.yml
  /wine_types:
    $ref: paths/wine_types.yml
  /wine_types/{wine_type}:
    $ref: paths/wine_types_{wine_type}.yml
  /wines:
    $ref: paths/wines.yml
  /wines/{wine}:
    $ref: paths/wines_{wine}.yml
  /grapes:
    $ref: paths/grapes.yml
  /grapes/{grape}:
    $ref: paths/grapes_{grape}.yml
  /producers:
    $ref: paths/producers.yml
  /producers/{producer}:
    $ref: paths/producers_{producer}.yml
  /regions:
    $ref: paths/regions.yml
  /regions/{region}:
    $ref: paths/regions_{region}.yml
  /countries:
    $ref: paths/countries.yml
  /countries/{country}:
    $ref: paths/countries_{country}.yml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT